import type { Questao } from "@/lib/enem-data";

const q = (
  id: string,
  area: Questao["area"],
  disciplina: string,
  assunto: string,
  dificuldade: Questao["dificuldade"],
  enunciado: string,
  alternativas: string[],
  correta: number,
  explicacao: string,
): Questao => ({
  id,
  area,
  disciplina,
  assunto,
  fonte: "Banco de treino Acelera ENEM — questão autoral",
  dificuldade,
  enunciado,
  alternativas,
  correta,
  explicacao,
});

export const QUESTOES_EXTRAS: Questao[] = [
  q(
    "mat-7",
    "matematica",
    "Matemática",
    "Regra de três",
    "facil",
    "Uma torneira enche 120 litros em 8 minutos. Mantida a mesma vazão, quantos litros serão colocados em 15 minutos?",
    ["180 L", "200 L", "225 L", "240 L", "300 L"],
    2,
    "A vazão é 15 L/min; em 15 minutos, 15 × 15 = 225 L.",
  ),
  q(
    "mat-8",
    "matematica",
    "Matemática",
    "Matemática financeira",
    "media",
    "Uma aplicação de R$ 800 rende juros simples de 2% ao mês durante 5 meses. Qual é o montante?",
    ["R$ 820", "R$ 860", "R$ 880", "R$ 900", "R$ 960"],
    2,
    "J = 800 × 0,02 × 5 = 80; montante = 800 + 80 = R$ 880.",
  ),
  q(
    "mat-9",
    "matematica",
    "Matemática",
    "Análise combinatória",
    "media",
    "Quantas senhas de três algarismos distintos podem ser formadas usando 1, 2, 3, 4 e 5?",
    ["10", "15", "20", "40", "60"],
    3,
    "São 5 escolhas para o primeiro, 4 para o segundo e 3 para o terceiro: 5 × 4 × 3 = 60.",
  ),
  q(
    "mat-10",
    "matematica",
    "Matemática",
    "Probabilidade",
    "facil",
    "Em uma turma com 12 estudantes, 7 praticam futebol e 5 praticam vôlei. Escolhendo um estudante ao acaso, a probabilidade de ele praticar vôlei é:",
    ["5%", "12%", "25%", "42%", "60%"],
    3,
    "Há 5 casos favoráveis em 12 possíveis: 5/12, aproximadamente 42%.",
  ),
  q(
    "mat-11",
    "matematica",
    "Matemática",
    "Geometria plana",
    "media",
    "Um terreno retangular mede 18 m por 25 m. A área desse terreno, em metros quadrados, é:",
    ["43", "86", "215", "360", "450"],
    4,
    "A área do retângulo é base × altura: 18 × 25 = 450 m².",
  ),
  q(
    "mat-12",
    "matematica",
    "Matemática",
    "Estatística",
    "media",
    "As temperaturas registradas foram 20, 22, 22, 24 e 27 °C. A mediana é:",
    ["20", "21", "22", "24", "27"],
    2,
    "Em uma lista ordenada com cinco valores, a mediana é o terceiro: 22 °C.",
  ),

  q(
    "lin-7",
    "linguagens",
    "Português",
    "Interpretação textual",
    "facil",
    "Em uma campanha, a frase “Doe um livro, compartilhe futuros” procura associar a doação principalmente à ideia de:",
    ["Competição", "Transformação social", "Consumo individual", "Humor", "Nostalgia"],
    1,
    "A campanha aproxima o ato de doar livros da possibilidade de ampliar oportunidades.",
  ),
  q(
    "lin-8",
    "linguagens",
    "Português",
    "Figuras de linguagem",
    "media",
    "Na frase “A cidade acordou inquieta”, a atribuição de uma ação humana à cidade caracteriza:",
    ["Metáfora", "Antítese", "Personificação", "Ironia", "Eufemismo"],
    2,
    "A cidade recebe uma característica humana, recurso chamado personificação ou prosopopeia.",
  ),
  q(
    "lin-9",
    "linguagens",
    "Literatura",
    "Gêneros textuais",
    "facil",
    "Uma resenha crítica se diferencia de um simples resumo porque apresenta:",
    [
      "Apenas datas",
      "Opinião argumentada sobre a obra",
      "Somente diálogos",
      "Instruções de uso",
      "Dados sem interpretação",
    ],
    1,
    "A resenha sintetiza a obra e também avalia seus aspectos com argumentos.",
  ),
  q(
    "lin-10",
    "linguagens",
    "Português",
    "Gramática aplicada ao texto",
    "media",
    "No período “Embora estivesse cansada, a pesquisadora continuou o experimento”, a palavra “embora” introduz uma ideia de:",
    ["Causa", "Conclusão", "Concessão", "Finalidade", "Comparação"],
    2,
    "A oração apresenta um fato que poderia impedir a ação, mas não a impede: concessão.",
  ),
  q(
    "lin-11",
    "linguagens",
    "Artes",
    "Linguagem não verbal",
    "media",
    "Uma charge combina imagem e texto para criticar um acontecimento atual. O efeito de sentido depende principalmente da:",
    [
      "Leitura literal isolada",
      "Relação entre elementos visuais e contexto",
      "Ausência de opinião",
      "Repetição de dados",
      "Tradução para outra língua",
    ],
    1,
    "A charge produz humor e crítica pela articulação entre imagem, palavras e contexto social.",
  ),
  q(
    "lin-12",
    "linguagens",
    "Inglês",
    "Interpretação",
    "facil",
    "The notice says: “Please keep the door closed to save energy.” The notice asks people to:",
    [
      "Open the door",
      "Paint the door",
      "Keep the door closed",
      "Replace the energy",
      "Leave the building",
    ],
    2,
    "A frase pede que a porta permaneça fechada para economizar energia.",
  ),

  q(
    "hum-7",
    "humanas",
    "História",
    "República",
    "media",
    "A Constituição de 1988 ficou conhecida como Constituição Cidadã por ampliar:",
    [
      "A censura",
      "Direitos sociais e participação democrática",
      "O poder militar",
      "A escravidão",
      "O voto censitário",
    ],
    1,
    "A Constituição consolidou direitos civis, políticos e sociais no período de redemocratização.",
  ),
  q(
    "hum-8",
    "humanas",
    "Geografia",
    "Globalização",
    "media",
    "A globalização contemporânea é marcada pela intensificação de:",
    [
      "Isolamento entre países",
      "Fluxos de mercadorias, capitais e informações",
      "Fronteiras naturais",
      "Economias autossuficientes",
      "Produção artesanal local בלבד",
    ],
    1,
    "As redes globais ampliam fluxos econômicos, tecnológicos, culturais e informacionais.",
  ),
  q(
    "hum-9",
    "humanas",
    "Sociologia",
    "Cidadania",
    "facil",
    "A cidadania plena envolve, de forma articulada:",
    [
      "Apenas direitos civis",
      "Direitos civis, políticos e sociais",
      "Somente deveres",
      "Exclusão política",
      "Privilégios hereditários",
    ],
    1,
    "A cidadania reúne diferentes dimensões de direitos e participação na vida coletiva.",
  ),
  q(
    "hum-10",
    "humanas",
    "Filosofia",
    "Ética",
    "media",
    "Uma decisão ética considera principalmente:",
    [
      "Apenas o benefício individual",
      "As consequências e os direitos das pessoas envolvidas",
      "A opinião da maioria em qualquer situação",
      "O lucro imediato",
      "A ausência de regras",
    ],
    1,
    "A reflexão ética pondera princípios, consequências e respeito à dignidade humana.",
  ),
  q(
    "hum-11",
    "humanas",
    "Geografia",
    "Meio ambiente",
    "media",
    "A expansão de áreas impermeabilizadas nas cidades tende a aumentar:",
    [
      "A infiltração da água",
      "O risco de alagamentos",
      "A cobertura vegetal",
      "A evapotranspiração",
      "A recarga natural dos rios",
    ],
    1,
    "As superfícies impermeáveis reduzem a infiltração e aceleram o escoamento superficial.",
  ),
  q(
    "hum-12",
    "humanas",
    "História",
    "Industrialização",
    "dificil",
    "A industrialização brasileira do século XX contribuiu para:",
    [
      "A redução da urbanização",
      "A concentração de empregos e população nas cidades",
      "O desaparecimento do setor de serviços",
      "O fim das desigualdades regionais",
      "A volta da economia colonial",
    ],
    1,
    "A industrialização intensificou a urbanização e deslocou população em busca de trabalho.",
  ),

  q(
    "nat-7",
    "natureza",
    "Biologia",
    "Saúde",
    "facil",
    "A vacinação contribui para a saúde coletiva porque:",
    [
      "Substitui toda higiene",
      "Estimula memória imunológica e reduz a circulação de agentes",
      "Causa a doença sempre",
      "Funciona somente em adultos",
      "Elimina a necessidade de atendimento",
    ],
    1,
    "Vacinas treinam o sistema imune e reduzem a transmissão quando há ampla cobertura.",
  ),
  q(
    "nat-8",
    "natureza",
    "Física",
    "Eletricidade",
    "media",
    "Um aparelho de 1000 W ligado durante 2 horas consome, aproximadamente:",
    ["0,2 kWh", "1 kWh", "2 kWh", "20 kWh", "200 kWh"],
    2,
    "1000 W = 1 kW; energia = 1 × 2 = 2 kWh.",
  ),
  q(
    "nat-9",
    "natureza",
    "Química",
    "Química orgânica",
    "facil",
    "O etanol pertence à função orgânica dos:",
    ["Ácidos carboxílicos", "Álcoois", "Aldeídos", "Ésteres", "Hidrocarbonetos"],
    1,
    "O etanol apresenta o grupo hidroxila ligado a carbono saturado, característica dos álcoois.",
  ),
  q(
    "nat-10",
    "natureza",
    "Biologia",
    "Ecologia",
    "media",
    "A retirada de um predador de uma cadeia alimentar pode provocar:",
    [
      "Nenhuma alteração",
      "Desequilíbrio nas populações das presas",
      "Aumento imediato de produtores",
      "Fim da fotossíntese",
      "Redução da energia solar",
    ],
    1,
    "A ausência do predador pode aumentar presas e alterar as relações tróficas do ecossistema.",
  ),
  q(
    "nat-11",
    "natureza",
    "Física",
    "Mecânica",
    "media",
    "Quando um passageiro é projetado para a frente numa travagem brusca, o fenómeno está relacionado à:",
    ["Inércia", "Refração", "Dilatação", "Pressão atmosférica", "Radioatividade"],
    0,
    "A tendência de manter o estado de movimento é explicada pela inércia.",
  ),
  q(
    "nat-12",
    "natureza",
    "Química",
    "Reações químicas",
    "dificil",
    "Em uma reação de combustão completa de um hidrocarboneto, os principais produtos são:",
    [
      "Água e gás carbônico",
      "Sal e oxigênio",
      "Nitrogênio e amônia",
      "Ácido e base",
      "Metano e hidrogênio",
    ],
    0,
    "A combustão completa de hidrocarbonetos produz CO₂ e H₂O na presença de oxigênio.",
  ),
  q(
    "mat-13",
    "matematica",
    "Matemática",
    "Funções",
    "media",
    "Se f(x) = 3x - 2, então f(5) é igual a:",
    ["8", "10", "13", "15", "17"],
    2,
    "f(5) = 3 × 5 - 2 = 13.",
  ),
  q(
    "mat-14",
    "matematica",
    "Matemática",
    "Equações",
    "facil",
    "A solução de 2x + 6 = 18 é:",
    ["4", "5", "6", "7", "8"],
    2,
    "2x = 12; portanto, x = 6.",
  ),
  q(
    "mat-15",
    "matematica",
    "Matemática",
    "Sistemas",
    "media",
    "No sistema x + y = 10 e x - y = 2, o valor de x é:",
    ["2", "4", "6", "8", "10"],
    2,
    "Somando as equações, 2x = 12; logo, x = 6.",
  ),
  q(
    "mat-16",
    "matematica",
    "Matemática",
    "Escalas",
    "media",
    "Num mapa na escala 1:100 000, 3 cm representam:",
    ["30 m", "300 m", "3 km", "30 km", "300 km"],
    2,
    "Cada centímetro representa 100 000 cm, ou 1 km; 3 cm representam 3 km.",
  ),
  q(
    "mat-17",
    "matematica",
    "Matemática",
    "Conversão de unidades",
    "facil",
    "Quantos mililitros correspondem a 2,5 litros?",
    ["25", "250", "2 500", "25 000", "0,25"],
    2,
    "1 litro equivale a 1 000 mL; 2,5 L equivalem a 2 500 mL.",
  ),
  q(
    "mat-18",
    "matematica",
    "Matemática",
    "Progressões",
    "dificil",
    "Uma sequência começa em 4 e soma 3 a cada termo. O sexto termo é:",
    ["16", "17", "19", "20", "22"],
    2,
    "O sexto termo é 4 + 5 × 3 = 19.",
  ),
  q(
    "mat-19",
    "matematica",
    "Matemática",
    "Logaritmos",
    "dificil",
    "O valor de log10(1000) é:",
    ["1", "2", "3", "10", "100"],
    2,
    "Como 10³ = 1000, o logaritmo é 3.",
  ),
  q(
    "mat-20",
    "matematica",
    "Matemática",
    "Trigonometria",
    "media",
    "Num triângulo retângulo, o seno de um ângulo é a razão entre:",
    [
      "cateto adjacente e hipotenusa",
      "cateto oposto e hipotenusa",
      "hipotenusa e cateto oposto",
      "os dois catetos",
      "a área e a base",
    ],
    1,
    "Seno = cateto oposto dividido pela hipotenusa.",
  ),
  q(
    "mat-21",
    "matematica",
    "Matemática",
    "Matrizes",
    "media",
    "A soma dos elementos da diagonal principal da matriz [[2,1],[4,5]] é:",
    ["3", "5", "6", "7", "12"],
    3,
    "A diagonal principal contém 2 e 5; a soma é 7.",
  ),
  q(
    "mat-22",
    "matematica",
    "Matemática",
    "Média ponderada",
    "media",
    "Uma prova vale peso 2 e um trabalho vale peso 1. Com notas 7 e 10, a média ponderada é:",
    ["7,0", "7,5", "8,0", "8,5", "9,0"],
    2,
    "(7 × 2 + 10 × 1)/3 = 8.",
  ),
  q(
    "mat-23",
    "matematica",
    "Matemática",
    "Juros compostos",
    "dificil",
    "R$ 1 000 aplicados a 10% ao ano, em juros compostos, resultam em quanto após 2 anos?",
    ["R$ 1 100", "R$ 1 200", "R$ 1 210", "R$ 1 220", "R$ 1 300"],
    2,
    "1 000 × 1,1² = R$ 1 210.",
  ),
  q(
    "mat-24",
    "matematica",
    "Matemática",
    "Polígonos",
    "facil",
    "A soma dos ângulos internos de um triângulo é:",
    ["90°", "180°", "270°", "360°", "540°"],
    1,
    "A soma dos ângulos internos de qualquer triângulo é 180°.",
  ),
  q(
    "mat-25",
    "matematica",
    "Matemática",
    "Cilindros",
    "media",
    "Um cilindro tem raio 2 cm e altura 5 cm. Usando π = 3, seu volume é:",
    ["15 cm³", "30 cm³", "45 cm³", "60 cm³", "90 cm³"],
    1,
    "V = πr²h = 3 × 4 × 5 = 60 cm³.",
  ),
  q(
    "mat-26",
    "matematica",
    "Matemática",
    "Probabilidade condicional",
    "dificil",
    "Em uma caixa há 3 bolas azuis e 2 verdes. Sem reposição, a chance de retirar duas azuis é:",
    ["10%", "20%", "30%", "40%", "60%"],
    2,
    "A probabilidade é 3/5 × 2/4 = 3/10 = 30%.",
  ),
  q(
    "mat-27",
    "matematica",
    "Matemática",
    "Inequações",
    "media",
    "A solução de x + 4 > 9 é:",
    ["x > 3", "x > 4", "x > 5", "x < 5", "x < 13"],
    2,
    "Subtraindo 4 dos dois lados, x > 5.",
  ),
  q(
    "mat-28",
    "matematica",
    "Matemática",
    "Notação científica",
    "facil",
    "O número 0,00045 escrito em notação científica é:",
    ["4,5 × 10⁻²", "4,5 × 10⁻³", "4,5 × 10⁻⁴", "45 × 10⁻⁴", "45 × 10⁻⁵"],
    2,
    "A vírgula desloca quatro casas: 4,5 × 10⁻⁴.",
  ),
  q(
    "mat-29",
    "matematica",
    "Matemática",
    "Cônicas",
    "dificil",
    "A representação gráfica de x² + y² = 9 é uma circunferência de raio:",
    ["1", "2", "3", "6", "9"],
    2,
    "A forma x² + y² = r² tem raio r = 3.",
  ),
  q(
    "mat-30",
    "matematica",
    "Matemática",
    "Gráficos",
    "media",
    "Num gráfico de barras, a altura de cada barra representa normalmente:",
    ["A legenda", "A frequência ou valor da categoria", "O título", "A fonte", "A unidade apenas"],
    1,
    "A escala vertical permite comparar os valores representados pelas barras.",
  ),

  q(
    "lin-13",
    "linguagens",
    "Português",
    "Intertextualidade",
    "media",
    "Quando um anúncio recria uma cena conhecida de uma obra para produzir humor, ocorre:",
    ["Intertextualidade", "Ambiguidade zero", "Neutralidade", "Apenas sinonímia", "Regionalismo"],
    0,
    "A recriação de um texto ou imagem reconhecível estabelece diálogo intertextual.",
  ),
  q(
    "lin-14",
    "linguagens",
    "Português",
    "Variação linguística",
    "facil",
    "A escolha de linguagem formal numa entrevista de emprego está relacionada principalmente à variação:",
    ["Histórica", "Regional", "Situacional", "Etária", "Geográfica"],
    2,
    "O registro muda conforme a situação comunicativa.",
  ),
  q(
    "lin-15",
    "linguagens",
    "Literatura",
    "Poesia",
    "media",
    "A repetição intencional de sons consonantais num poema é chamada:",
    ["Aliteração", "Hipérbole", "Paradoxo", "Metonímia", "Antonomásia"],
    0,
    "Aliteração é a repetição expressiva de sons consonantais.",
  ),
  q(
    "lin-16",
    "linguagens",
    "Literatura",
    "Romantismo",
    "media",
    "Uma característica frequente da primeira geração romântica brasileira é:",
    [
      "Nacionalismo e indianismo",
      "Culto à máquina",
      "Objetividade científica",
      "Antirromantismo",
      "Universalismo medieval",
    ],
    0,
    "A primeira geração valorizou a identidade nacional e a figura do indígena.",
  ),
  q(
    "lin-17",
    "linguagens",
    "Português",
    "Semântica",
    "facil",
    "Em “Ele tem um coração de pedra”, a expressão destaca sentido:",
    ["Literal", "Metafórico", "Técnico", "Denotativo", "Científico"],
    1,
    "A expressão usa metáfora para indicar insensibilidade.",
  ),
  q(
    "lin-18",
    "linguagens",
    "Publicidade",
    "Argumentação",
    "media",
    "O uso de depoimentos de consumidores num anúncio busca produzir efeito de:",
    [
      "Autoridade e identificação",
      "Contradição matemática",
      "Silêncio",
      "Neutralidade",
      "Distanciamento",
    ],
    0,
    "Depoimentos funcionam como prova social e aproximam o público da mensagem.",
  ),
  q(
    "lin-19",
    "linguagens",
    "Artes",
    "Patrimônio cultural",
    "media",
    "O patrimônio imaterial inclui principalmente:",
    [
      "Apenas edifícios",
      "Saberes, celebrações e práticas culturais",
      "Somente pinturas",
      "Objetos industriais",
      "Estradas federais",
    ],
    1,
    "Patrimônio imaterial envolve práticas, saberes, festas e expressões coletivas.",
  ),
  q(
    "lin-20",
    "linguagens",
    "Educação Física",
    "Corpo e sociedade",
    "facil",
    "A compreensão das práticas corporais como cultura reconhece que elas:",
    [
      "São iguais em todos os grupos",
      "Expressam valores e identidades sociais",
      "Não possuem história",
      "Dependem apenas de genética",
      "Não mudam no tempo",
    ],
    1,
    "Jogos, danças e esportes são práticas construídas socialmente.",
  ),
  q(
    "lin-21",
    "linguagens",
    "Português",
    "Coesão",
    "facil",
    "O pronome “isso” em um texto pode atuar como recurso de:",
    ["Retomada de informação", "Mudança de gênero", "Rima", "Ironia obrigatória", "Tradução"],
    0,
    "Pronomes podem retomar ideias apresentadas anteriormente, mantendo a coesão.",
  ),
  q(
    "lin-22",
    "linguagens",
    "Inglês",
    "Interpretação",
    "facil",
    "In “The city is greener today”, the word “greener” means:",
    ["Menor", "Mais verde", "Mais antiga", "Mais rápida", "Mais distante"],
    1,
    "O sufixo -er indica comparação: mais verde.",
  ),
  q(
    "lin-23",
    "linguagens",
    "Português",
    "Gêneros digitais",
    "media",
    "Uma hashtag em uma campanha digital ajuda a:",
    [
      "Agrupar e localizar publicações",
      "Apagar comentários",
      "Impedir leitura",
      "Substituir imagens",
      "Traduzir automaticamente",
    ],
    0,
    "A hashtag indexa conteúdos e facilita a participação em torno de um tema.",
  ),
  q(
    "lin-24",
    "linguagens",
    "Literatura",
    "Realismo",
    "dificil",
    "O Realismo brasileiro tende a privilegiar:",
    [
      "Idealização amorosa",
      "Análise crítica da sociedade",
      "Misticismo medieval",
      "Heroísmo nacional",
      "Fantasia infantil",
    ],
    1,
    "O Realismo observa relações sociais e psicológicas de forma crítica.",
  ),
  q(
    "lin-25",
    "linguagens",
    "Português",
    "Pontuação",
    "facil",
    "Os dois-pontos podem introduzir:",
    [
      "Uma explicação ou enumeração",
      "Somente uma pergunta",
      "Um verbo",
      "Uma nova língua",
      "Um sujeito obrigatório",
    ],
    0,
    "Os dois-pontos anunciam explicação, esclarecimento ou enumeração.",
  ),
  q(
    "lin-26",
    "linguagens",
    "Artes",
    "Fotografia",
    "media",
    "O enquadramento de uma fotografia contribui para:",
    [
      "Definir o que será destacado na cena",
      "Eliminar todo sentido",
      "Impedir interpretação",
      "Tornar a imagem sempre objetiva",
      "Substituir a luz",
    ],
    0,
    "O enquadramento orienta o olhar e seleciona elementos da representação.",
  ),
  q(
    "lin-27",
    "linguagens",
    "Português",
    "Discurso",
    "media",
    "Ao transformar fala direta em indireta, o narrador passa a:",
    [
      "Reproduzir exatamente a voz",
      "Relatar a fala a partir de sua própria construção",
      "Eliminar o sentido",
      "Usar apenas interjeições",
      "Mudar o idioma",
    ],
    1,
    "No discurso indireto, o narrador incorpora a fala ao seu relato.",
  ),
  q(
    "lin-28",
    "linguagens",
    "Linguística",
    "Preconceito linguístico",
    "dificil",
    "O preconceito linguístico ocorre quando:",
    [
      "Toda língua muda",
      "Uma variedade é julgada inferior por razões sociais",
      "Há tradução",
      "Uma palavra tem dois sentidos",
      "Se usa linguagem técnica",
    ],
    1,
    "O julgamento de variedades linguísticas costuma refletir relações sociais de poder.",
  ),
  q(
    "lin-29",
    "linguagens",
    "Português",
    "Argumentação",
    "media",
    "Um argumento de autoridade baseia-se em:",
    [
      "Citar fonte ou especialista pertinente",
      "Repetir a conclusão",
      "Usar letra maiúscula",
      "Fazer uma pergunta",
      "Evitar evidências",
    ],
    0,
    "A autoridade pertinente oferece respaldo ao ponto defendido.",
  ),
  q(
    "lin-30",
    "linguagens",
    "Português",
    "Funções da linguagem",
    "facil",
    "Quando o texto explica o significado de uma palavra, predomina a função:",
    ["Metalinguística", "Emotiva", "Conativa", "Poética", "Fática"],
    0,
    "A linguagem usada para explicar a própria linguagem é metalinguística.",
  ),

  q(
    "hum-13",
    "humanas",
    "História",
    "Escravidão",
    "media",
    "A abolição da escravidão no Brasil em 1888 não foi acompanhada de:",
    [
      "Políticas amplas de inclusão social dos libertos",
      "Pressões abolicionistas",
      "Mudanças no trabalho",
      "Resistência negra",
      "Debate político",
    ],
    0,
    "A Lei Áurea não criou políticas de reparação ou integração socioeconômica.",
  ),
  q(
    "hum-14",
    "humanas",
    "Geografia",
    "População",
    "facil",
    "O crescimento vegetativo corresponde à diferença entre:",
    [
      "Imigração e emigração",
      "Nascimentos e mortes",
      "População rural e urbana",
      "Exportação e importação",
      "Renda e consumo",
    ],
    1,
    "Crescimento vegetativo = taxa de natalidade menos taxa de mortalidade.",
  ),
  q(
    "hum-15",
    "humanas",
    "Sociologia",
    "Desigualdade",
    "media",
    "A desigualdade social pode ser analisada considerando:",
    [
      "Apenas diferenças naturais",
      "Acesso desigual a renda, direitos e oportunidades",
      "Somente preferências",
      "O clima",
      "A idade média",
    ],
    1,
    "Desigualdades são produzidas por estruturas de acesso a recursos e direitos.",
  ),
  q(
    "hum-16",
    "humanas",
    "Filosofia",
    "Conhecimento",
    "dificil",
    "Para Sócrates, reconhecer a própria ignorância era importante porque favorecia:",
    [
      "A busca pelo conhecimento",
      "A rejeição do diálogo",
      "A certeza absoluta",
      "A ausência de reflexão",
      "O poder militar",
    ],
    0,
    "A consciência dos limites do saber abre espaço para o diálogo e a investigação.",
  ),
  q(
    "hum-17",
    "humanas",
    "História",
    "Ditadura militar",
    "media",
    "A censura durante a ditadura militar brasileira atingia principalmente:",
    [
      "A circulação de críticas e informações",
      "Apenas produtos agrícolas",
      "Somente o comércio exterior",
      "As estações do ano",
      "A produção de alimentos",
    ],
    0,
    "A censura restringia manifestações, imprensa, artes e circulação de ideias críticas.",
  ),
  q(
    "hum-18",
    "humanas",
    "Geografia",
    "Clima",
    "facil",
    "O clima de uma região resulta da observação de condições atmosféricas ao longo de:",
    ["Poucos minutos", "Longo período", "Uma única chuva", "Um dia isolado", "Uma maré"],
    1,
    "Clima é o padrão atmosférico observado durante longos períodos.",
  ),
  q(
    "hum-19",
    "humanas",
    "Economia",
    "Inflação",
    "media",
    "A inflação representa, de modo geral:",
    [
      "Queda contínua dos preços",
      "Aumento generalizado dos preços",
      "Apenas aumento salarial",
      "Fim do consumo",
      "Redução da moeda em circulação sempre",
    ],
    1,
    "Inflação é o aumento persistente e generalizado do nível de preços.",
  ),
  q(
    "hum-20",
    "humanas",
    "Política",
    "Democracia",
    "facil",
    "Eleições periódicas e participação popular são elementos associados à:",
    ["Democracia", "Autocracia", "Censura", "Colonização", "Escravidão"],
    0,
    "A democracia inclui participação política e mecanismos de escolha e controle.",
  ),
  q(
    "hum-21",
    "humanas",
    "Geografia",
    "Migrações",
    "media",
    "Um fator de expulsão migratória pode ser:",
    [
      "Conflito ou falta de oportunidades",
      "Aumento de lazer",
      "Melhoria do transporte turístico",
      "Oferta de férias",
      "Paisagem bonita",
    ],
    0,
    "Conflitos e falta de trabalho podem levar pessoas a deixar um território.",
  ),
  q(
    "hum-22",
    "humanas",
    "Sociologia",
    "Cultura",
    "facil",
    "A cultura é melhor compreendida como:",
    [
      "Conjunto aprendido de valores e práticas",
      "Herança apenas biológica",
      "Fenómeno igual em todo lugar",
      "Algo sem mudanças",
      "Comportamento instintivo",
    ],
    0,
    "Cultura é aprendida e compartilhada, apresentando diversidade e transformação.",
  ),
  q(
    "hum-23",
    "humanas",
    "História",
    "Revolução Industrial",
    "media",
    "A Primeira Revolução Industrial teve como símbolo energético principal:",
    ["Carvão mineral", "Urânio", "Energia solar", "Vento", "Biocombustível"],
    0,
    "O carvão alimentou máquinas a vapor e transformou a produção industrial.",
  ),
  q(
    "hum-24",
    "humanas",
    "Filosofia",
    "Política",
    "dificil",
    "A ideia de separação de poderes busca:",
    [
      "Evitar a concentração absoluta de autoridade",
      "Extinguir leis",
      "Impedir eleições",
      "Eliminar o Judiciário",
      "Centralizar decisões",
    ],
    0,
    "A divisão entre poderes cria controles e limitações recíprocas.",
  ),
  q(
    "hum-25",
    "humanas",
    "Geografia",
    "Agricultura",
    "media",
    "A agricultura familiar destaca-se por:",
    [
      "Produção realizada predominantemente pela família",
      "Uso exclusivo de grandes latifúndios",
      "Ausência de mercados",
      "Produção sempre mecanizada",
      "Não produzir alimentos",
    ],
    0,
    "A mão de obra e a gestão familiar são características centrais dessa forma de produção.",
  ),
  q(
    "hum-26",
    "humanas",
    "Meio ambiente",
    "Sustentabilidade",
    "facil",
    "Desenvolvimento sustentável procura conciliar:",
    [
      "Economia, sociedade e proteção ambiental",
      "Consumo e desperdício",
      "Crescimento sem limites",
      "Lucro e poluição",
      "Tecnologia e exclusão",
    ],
    0,
    "Sustentabilidade articula necessidades presentes e preservação das condições futuras.",
  ),
  q(
    "hum-27",
    "humanas",
    "História",
    "Colonialismo",
    "dificil",
    "O colonialismo europeu esteve relacionado a:",
    [
      "Dominação territorial e exploração de recursos",
      "Igualdade entre impérios",
      "Fim do comércio",
      "Autonomia dos povos colonizados",
      "Desindustrialização europeia",
    ],
    0,
    "A colonização envolveu controle político, exploração econômica e imposição cultural.",
  ),
  q(
    "hum-28",
    "humanas",
    "Sociologia",
    "Trabalho",
    "media",
    "A divisão social do trabalho pode aumentar a produtividade por meio da:",
    [
      "Especialização de tarefas",
      "Eliminação de cooperação",
      "Ausência de funções",
      "Redução do conhecimento",
      "Proibição de ferramentas",
    ],
    0,
    "A especialização distribui tarefas e pode tornar a produção mais eficiente.",
  ),
  q(
    "hum-29",
    "humanas",
    "Geografia",
    "Território",
    "media",
    "Território é um espaço marcado principalmente por:",
    [
      "Relações de poder e apropriação",
      "Ausência de sociedade",
      "Somente elementos naturais",
      "Distância do Equador",
      "Temperatura",
    ],
    0,
    "O conceito de território envolve controle, poder, identidade e uso do espaço.",
  ),
  q(
    "hum-30",
    "humanas",
    "História",
    "Patrimônio",
    "facil",
    "A preservação de patrimônios históricos contribui para:",
    [
      "Manter memórias e referências coletivas",
      "Apagar conflitos",
      "Impedir pesquisas",
      "Substituir a cultura",
      "Eliminar identidades",
    ],
    0,
    "Patrimônios preservam memórias e ajudam a interpretar experiências coletivas.",
  ),

  q(
    "nat-13",
    "natureza",
    "Biologia",
    "Citologia",
    "facil",
    "A organela responsável pela produção de energia na célula é a:",
    ["Mitocôndria", "Ribossomo", "Parede celular", "Vacuólo", "Membrana"],
    0,
    "A mitocôndria participa da respiração celular e produção de ATP.",
  ),
  q(
    "nat-14",
    "natureza",
    "Biologia",
    "Genética",
    "media",
    "O DNA é responsável principalmente por:",
    [
      "Armazenar informação genética",
      "Produzir luz",
      "Digerir alimentos",
      "Transportar oxigênio",
      "Regular a temperatura externa",
    ],
    0,
    "O DNA armazena instruções hereditárias dos organismos.",
  ),
  q(
    "nat-15",
    "natureza",
    "Física",
    "Ondas",
    "media",
    "O som não se propaga no vácuo porque precisa de:",
    ["Um meio material", "Luz solar", "Campo magnético", "Gravidade zero", "Temperatura constante"],
    0,
    "O som é uma onda mecânica e necessita de partículas para vibrar.",
  ),
  q(
    "nat-16",
    "natureza",
    "Química",
    "Tabela periódica",
    "facil",
    "Elementos de uma mesma família da tabela periódica tendem a apresentar:",
    [
      "Propriedades químicas semelhantes",
      "Mesma massa",
      "Mesmo número de nêutrons",
      "Mesma fase sempre",
      "Mesma cor",
    ],
    0,
    "A configuração dos elétrons de valência explica semelhanças químicas.",
  ),
  q(
    "nat-17",
    "natureza",
    "Biologia",
    "Evolução",
    "dificil",
    "A seleção natural atua favorecendo características que:",
    [
      "Aumentam a sobrevivência e reprodução no ambiente",
      "Surgem por necessidade consciente",
      "São sempre adquiridas por treino",
      "Eliminam toda variação",
      "Não têm relação com o ambiente",
    ],
    0,
    "Características vantajosas podem aumentar a contribuição reprodutiva de seus portadores.",
  ),
  q(
    "nat-18",
    "natureza",
    "Física",
    "Termologia",
    "facil",
    "A transferência de calor por contacto direto entre partículas é chamada:",
    ["Condução", "Convecção", "Irradiação", "Reflexão", "Dispersão"],
    0,
    "Condução ocorre pela interação direta entre partículas do material.",
  ),
  q(
    "nat-19",
    "natureza",
    "Química",
    "pH",
    "media",
    "Uma solução com pH 3 é classificada como:",
    ["Ácida", "Básica", "Neutra", "Metálica", "Saturada"],
    0,
    "Valores de pH menores que 7 indicam acidez.",
  ),
  q(
    "nat-20",
    "natureza",
    "Biologia",
    "Ciclos biogeoquímicos",
    "media",
    "A fotossíntese retira da atmosfera principalmente:",
    ["Gás carbônico", "Oxigênio", "Nitrogênio molecular", "Hélio", "Vapor de mercúrio"],
    0,
    "Na fotossíntese, plantas utilizam CO₂ e água para formar matéria orgânica.",
  ),
  q(
    "nat-21",
    "natureza",
    "Física",
    "Óptica",
    "facil",
    "A reflexão regular da luz ocorre quando ela incide em uma superfície:",
    ["Lisa e polida", "Sempre rugosa", "Transparente e gasosa", "Sem matéria", "Em movimento"],
    0,
    "Superfícies lisas preservam uma direção organizada para a reflexão.",
  ),
  q(
    "nat-22",
    "natureza",
    "Química",
    "Estequiometria",
    "dificil",
    "Na reação 2H₂ + O₂ → 2H₂O, a proporção entre moléculas de H₂ e O₂ é:",
    ["1:1", "2:1", "1:2", "2:2", "3:1"],
    1,
    "A equação balanceada indica duas moléculas de H₂ para uma de O₂.",
  ),
  q(
    "nat-23",
    "natureza",
    "Biologia",
    "Sistema circulatório",
    "facil",
    "As artérias conduzem o sangue:",
    [
      "Para fora do coração",
      "Sempre rico em gás carbônico",
      "Para dentro do coração",
      "Somente nos pulmões",
      "Apenas no cérebro",
    ],
    0,
    "Artérias levam sangue para os tecidos; a oxigenação depende do circuito.",
  ),
  q(
    "nat-24",
    "natureza",
    "Física",
    "Pressão",
    "media",
    "A pressão exercida por uma força aumenta quando a área de contacto:",
    ["Diminui", "Aumenta", "Fica nula", "Muda de cor", "É isolada"],
    0,
    "Para a mesma força, p = F/A; reduzir a área aumenta a pressão.",
  ),
  q(
    "nat-25",
    "natureza",
    "Química",
    "Separação de misturas",
    "facil",
    "Para separar areia e água, o método mais adequado é:",
    ["Filtração", "Destilação fracionada", "Cromatografia", "Fusão", "Sublimação"],
    0,
    "A filtração retém o sólido insolúvel e permite a passagem do líquido.",
  ),
  q(
    "nat-26",
    "natureza",
    "Biologia",
    "Imunologia",
    "media",
    "Os anticorpos são moléculas produzidas principalmente por:",
    ["Linfócitos B", "Hemácias", "Plaquetas", "Neurônios", "Osteócitos"],
    0,
    "Linfócitos B diferenciados produzem anticorpos específicos.",
  ),
  q(
    "nat-27",
    "natureza",
    "Física",
    "Magnetismo",
    "media",
    "Uma bússola orienta-se aproximadamente no sentido:",
    ["Norte-Sul", "Leste-Oeste sempre", "Vertical apenas", "Do centro para a borda", "Aleatório"],
    0,
    "A agulha magnética alinha-se aproximadamente ao campo magnético terrestre.",
  ),
  q(
    "nat-28",
    "natureza",
    "Química",
    "Oxirredução",
    "dificil",
    "Oxidação é o processo que envolve:",
    [
      "Perda de elétrons",
      "Ganho de elétrons",
      "Perda de prótons sempre",
      "Ganho de nêutrons",
      "Ausência de reação",
    ],
    0,
    "Na oxidação, uma espécie perde elétrons; na redução, ganha.",
  ),
  q(
    "nat-29",
    "natureza",
    "Biologia",
    "Ecologia",
    "media",
    "A biodiversidade de um ecossistema inclui a variedade de:",
    [
      "Genes, espécies e ecossistemas",
      "Apenas animais",
      "Apenas plantas",
      "Somente climas",
      "Minerais industriais",
    ],
    0,
    "Biodiversidade contempla diversidade genética, de espécies e de ecossistemas.",
  ),
  q(
    "nat-30",
    "natureza",
    "Física",
    "Radioatividade",
    "dificil",
    "A meia-vida de uma substância radioativa é o tempo necessário para:",
    [
      "Metade dos núcleos se desintegrar",
      "Toda a substância desaparecer",
      "A massa dobrar",
      "A temperatura zerar",
      "A energia ser criada",
    ],
    0,
    "Meia-vida corresponde à redução de metade dos núcleos radioativos.",
  ),
];
