import type { Bruta } from "./tipos";

export const HUMANAS: Bruta[] = [
  ["hum-1", "História", "Brasil Colônia", "facil",
    "O sistema de capitanias hereditárias, implantado no Brasil em 1534, tinha como objetivo principal",
    ["distribuir terras a povos indígenas", "transferir a Portugal o custo direto da ocupação, delegando-a a donatários", "criar repúblicas autônomas", "abolir o trabalho compulsório", "estimular a industrialização"], 1,
    "A Coroa delegou a particulares a colonização, reduzindo custos e riscos do Estado português.", "Inspirada no ENEM 2017"],
  ["hum-2", "História", "Escravidão", "media",
    "A Lei Áurea (1888) é considerada insuficiente por historiadores porque",
    ["não libertou nenhum escravizado", "aboliu a escravidão sem políticas de inclusão dos libertos", "restaurou o tráfico atlântico", "criou cotas de trabalho para libertos", "garantiu terras a todos os libertos"], 1,
    "A abolição ocorreu sem reparação, acesso à terra ou educação, perpetuando desigualdades.", "Inspirada no ENEM 2019"],
  ["hum-3", "História", "Era Vargas", "media",
    "O Estado Novo (1937-1945) caracterizou-se por",
    ["ampla liberdade partidária", "centralização autoritária, censura e propaganda oficial", "eleições diretas anuais", "descentralização federativa", "abertura política plena"], 1,
    "Getúlio Vargas fechou o Congresso, censurou a imprensa (DIP) e concentrou poderes.", "Inspirada no ENEM 2018"],
  ["hum-4", "História", "Ditadura Militar", "media",
    "O AI-5, de 1968, representou",
    ["o fim da censura no Brasil", "o endurecimento do regime, com fechamento do Congresso e suspensão de direitos", "a convocação de eleições diretas", "a anistia de presos políticos", "a criação do voto feminino"], 1,
    "O Ato Institucional nº 5 inaugurou a fase mais repressiva da ditadura militar.", "Inspirada no ENEM 2020"],
  ["hum-5", "História", "Redemocratização", "facil",
    "O movimento Diretas Já (1983-1984) reivindicava",
    ["a volta da monarquia", "eleições diretas para presidente da República", "o fechamento do Congresso", "a criação do AI-5", "o fim do voto feminino"], 1,
    "A campanha pedia eleição direta para presidente, então feita por colégio eleitoral.", "Inspirada no ENEM 2016"],
  ["hum-6", "História", "História Geral", "media",
    "A Revolução Industrial inglesa do século XVIII resultou, entre outros fatores, de",
    ["ausência de mão de obra disponível", "acúmulo de capital, cercamentos e inovações técnicas", "proibição do comércio exterior", "fim das cidades", "retorno ao feudalismo"], 1,
    "Capital acumulado, êxodo rural provocado pelos cercamentos e novas máquinas impulsionaram a industrialização.", "Inspirada no ENEM 2017"],
  ["hum-7", "História", "História Geral", "media",
    "A Revolução Francesa (1789) difundiu o lema",
    ["\"Ordem e Progresso\"", "\"Liberdade, Igualdade e Fraternidade\"", "\"Pão, Terra e Paz\"", "\"Deus, Pátria e Família\"", "\"Proletários, uni-vos\""], 1,
    "O lema sintetiza os princípios iluministas que orientaram a revolução burguesa francesa.", "Inspirada no ENEM 2015"],
  ["hum-8", "História", "Guerra Fria", "media",
    "A Guerra Fria (1947-1991) foi marcada por",
    ["confronto militar direto entre EUA e URSS", "disputa ideológica, corrida armamentista e conflitos periféricos", "aliança econômica entre os dois blocos", "ausência de espionagem", "unificação política do mundo"], 1,
    "O conflito foi indireto: corrida armamentista, espacial e guerras localizadas.", "Inspirada no ENEM 2018"],
  ["hum-9", "Geografia", "Urbanização", "media",
    "A metropolização brasileira produziu, sobretudo a partir de 1970,",
    ["esvaziamento das cidades", "periferização e segregação socioespacial", "fim das favelas", "redução da população urbana", "distribuição igualitária de infraestrutura"], 1,
    "O crescimento urbano acelerado empurrou a população pobre para periferias com pouca infraestrutura.", "Inspirada no ENEM 2019"],
  ["hum-10", "Geografia", "Meio ambiente", "media",
    "O desmatamento na Amazônia contribui para a redução das chuvas no Centro-Sul porque afeta",
    ["as correntes marítimas frias", "os \"rios voadores\", massas de umidade transportadas pela floresta", "a inclinação do eixo terrestre", "a salinidade dos oceanos", "o campo magnético"], 1,
    "A evapotranspiração da floresta gera umidade transportada por correntes aéreas para outras regiões.", "Inspirada no ENEM 2021"],
  ["hum-11", "Geografia", "Clima", "facil",
    "As ilhas de calor urbanas são explicadas principalmente por",
    ["excesso de áreas verdes", "impermeabilização do solo, concreto e poluição", "proximidade de geleiras", "baixa densidade populacional", "chuvas constantes"], 1,
    "Materiais urbanos absorvem calor e a falta de vegetação eleva a temperatura no centro das cidades.", "Inspirada no ENEM 2017"],
  ["hum-12", "Geografia", "Agropecuária", "media",
    "O agronegócio brasileiro é criticado quando",
    ["adota tecnologia de plantio", "avança sobre áreas protegidas e concentra terra e renda", "exporta commodities", "gera empregos formais", "usa irrigação eficiente"], 1,
    "As críticas se dirigem à concentração fundiária e ao avanço sobre biomas e territórios tradicionais.", "Inspirada no ENEM 2020"],
  ["hum-13", "Geografia", "Migrações", "media",
    "As migrações internas no Brasil no século XX tiveram como principal fluxo",
    ["Sudeste → Norte", "Nordeste → Sudeste", "Sul → Nordeste", "Centro-Oeste → Sul", "Norte → Nordeste"], 1,
    "A industrialização do Sudeste atraiu grande contingente de migrantes nordestinos.", "Inspirada no ENEM 2016"],
  ["hum-14", "Geografia", "Globalização", "media",
    "A globalização é frequentemente descrita como desigual porque",
    ["conecta todos os territórios da mesma forma", "integra seletivamente regiões, ampliando disparidades", "eliminou fronteiras políticas", "reduziu o comércio internacional", "acabou com as empresas transnacionais"], 1,
    "Fluxos de capital e informação privilegiam certos territórios, aprofundando desigualdades.", "Inspirada no ENEM 2018"],
  ["hum-15", "Geografia", "Energia", "media",
    "A matriz elétrica brasileira é considerada relativamente limpa porque",
    ["depende quase toda do carvão", "tem forte participação de hidrelétricas e crescimento de eólica e solar", "usa apenas energia nuclear", "não gera impacto ambiental algum", "importa toda a energia consumida"], 1,
    "Fontes renováveis, especialmente a hídrica, predominam, embora causem impactos socioambientais.", "Inspirada no ENEM 2022"],
  ["hum-16", "Geografia", "Cartografia", "facil",
    "Em um mapa, a legenda serve para",
    ["indicar a data de impressão", "explicar o significado dos símbolos e cores usados", "definir a escala automaticamente", "substituir o título", "medir distâncias reais"], 1,
    "A legenda decodifica os símbolos cartográficos, permitindo a leitura do mapa.", "Inspirada no ENEM 2015"],
  ["hum-17", "Filosofia", "Filosofia antiga", "media",
    "O método socrático (maiêutica) consiste em",
    ["impor verdades ao interlocutor", "conduzir o interlocutor a perguntas que revelem suas contradições", "recorrer a oráculos", "provar teoremas matemáticos", "escrever tratados dogmáticos"], 1,
    "Sócrates conduzia o diálogo por perguntas para que o interlocutor \"desse à luz\" o conhecimento.", "Inspirada no ENEM 2017"],
  ["hum-18", "Filosofia", "Contratualismo", "media",
    "Para Thomas Hobbes, o Estado é necessário porque",
    ["o ser humano é naturalmente pacífico", "no estado de natureza haveria guerra de todos contra todos", "a propriedade é natural e sagrada", "a vontade geral é infalível", "a religião substitui a política"], 1,
    "Em Leviatã, o pacto social transfere poder ao soberano para evitar a guerra generalizada.", "Inspirada no ENEM 2019"],
  ["hum-19", "Filosofia", "Ética", "media",
    "O imperativo categórico de Kant estabelece que se deve agir",
    ["conforme o interesse pessoal", "segundo máxima que se possa querer como lei universal", "conforme o costume local", "para maximizar o prazer imediato", "obedecendo apenas à autoridade"], 1,
    "A ética kantiana é deontológica: o critério é a universalização da máxima da ação.", "Inspirada no ENEM 2018"],
  ["hum-20", "Filosofia", "Filosofia política", "media",
    "Para Montesquieu, a garantia da liberdade política depende",
    ["da concentração de poderes", "da separação entre Executivo, Legislativo e Judiciário", "do absolutismo esclarecido", "da abolição das leis", "do poder hereditário"], 1,
    "Em O Espírito das Leis, a divisão de poderes evita o abuso pelo controle mútuo.", "Inspirada no ENEM 2016"],
  ["hum-21", "Sociologia", "Clássicos", "media",
    "Para Émile Durkheim, os fatos sociais caracterizam-se por serem",
    ["individuais e voluntários", "exteriores, coercitivos e gerais", "irracionais e imprevisíveis", "exclusivamente econômicos", "naturais e biológicos"], 1,
    "Durkheim define o fato social por exterioridade, coercitividade e generalidade.", "Inspirada no ENEM 2017"],
  ["hum-22", "Sociologia", "Trabalho", "media",
    "Para Karl Marx, a mais-valia corresponde",
    ["ao salário pago ao trabalhador", "ao valor produzido pelo trabalhador que é apropriado pelo capitalista", "ao lucro do comércio internacional", "ao imposto pago ao Estado", "à poupança do trabalhador"], 1,
    "A mais-valia é o valor excedente gerado pelo trabalho e apropriado pelo dono dos meios de produção.", "Inspirada no ENEM 2019"],
  ["hum-23", "Sociologia", "Cultura", "media",
    "O etnocentrismo pode ser definido como",
    ["respeito às diferenças culturais", "julgar outras culturas a partir dos valores da própria cultura", "estudo científico das culturas", "mistura de culturas distintas", "defesa do relativismo cultural"], 1,
    "O etnocentrismo toma a própria cultura como medida universal, gerando preconceito.", "Inspirada no ENEM 2018"],
  ["hum-24", "Sociologia", "Cidadania", "facil",
    "Segundo a classificação de T. H. Marshall, o direito ao voto integra os direitos",
    ["civis", "políticos", "sociais", "difusos", "naturais"], 1,
    "Direitos políticos referem-se à participação no poder: votar e ser votado.", "Inspirada no ENEM 2020"],
  ["hum-25", "Sociologia", "Movimentos sociais", "media",
    "Movimentos sociais contemporâneos, como os de mulheres e negros, atuam principalmente pela",
    ["restrição de direitos", "ampliação do reconhecimento e da igualdade de direitos", "extinção do Estado", "privatização das escolas", "redução da participação política"], 1,
    "Esses movimentos lutam por reconhecimento identitário e por políticas de igualdade.", "Inspirada no ENEM 2021"],
  ["hum-26", "Sociologia", "Desigualdade", "media",
    "O conceito de \"racismo estrutural\" indica que o racismo",
    ["ocorre apenas em atos individuais isolados", "está incorporado às instituições e às práticas sociais cotidianas", "desapareceu após 1888", "é um fenômeno exclusivamente estrangeiro", "só existe na esfera jurídica"], 1,
    "O racismo estrutural aponta que desigualdades raciais são reproduzidas por instituições e normas sociais.", "Inspirada no ENEM 2022"],
  ["hum-27", "Geografia", "Economia", "media",
    "A dependência da exportação de commodities torna a economia brasileira vulnerável porque",
    ["os preços internacionais são estáveis", "oscilações de preço no mercado externo afetam diretamente a receita nacional", "não há concorrência global", "commodities não são exportadas", "o câmbio é fixo"], 1,
    "Commodities têm preços voláteis, o que expõe o país a choques externos.", "Inspirada no ENEM 2019"],
  ["hum-28", "História", "Povos indígenas", "media",
    "A demarcação de terras indígenas é prevista na Constituição de 1988 como forma de",
    ["assimilação forçada", "reconhecimento dos direitos originários sobre as terras tradicionalmente ocupadas", "concessão temporária de posse", "criação de reservas particulares", "expansão da fronteira agrícola"], 1,
    "O artigo 231 reconhece a organização social, os costumes e os direitos originários sobre suas terras.", "Inspirada no ENEM 2020"],
  ["hum-29", "Geografia", "Relações de poder", "media",
    "O conceito de \"geopolítica dos recursos\" ajuda a explicar conflitos relacionados a",
    ["moda e entretenimento", "petróleo, água e minerais estratégicos", "línguas oficiais", "calendários religiosos", "arquitetura urbana"], 1,
    "O controle de recursos estratégicos é fonte recorrente de disputas internacionais.", "Inspirada no ENEM 2018"],
  ["hum-30", "Filosofia", "Filosofia contemporânea", "dificil",
    "A crítica da Escola de Frankfurt à \"indústria cultural\" sustenta que ela",
    ["amplia a autonomia crítica do público", "padroniza bens culturais e transforma cultura em mercadoria", "elimina a publicidade", "impede o consumo de massa", "valoriza apenas a arte erudita"], 1,
    "Adorno e Horkheimer denunciam a padronização cultural que favorece a passividade do público.", "Inspirada no ENEM 2021"],
];
