import type { Bruta } from "./tipos";

export const LINGUAGENS: Bruta[] = [
  [
    "lin-1",
    "Português",
    "Funções da linguagem",
    "facil",
    '"Compre já! Aproveite a última chance de garantir o seu!" — Nesse anúncio, a função da linguagem predominante é',
    ["referencial", "emotiva", "conativa", "metalinguística", "fática"],
    2,
    "A função conativa (ou apelativa) busca convencer o interlocutor, marcada por verbos no imperativo.",
    "Inspirada no ENEM 2019",
  ],
  [
    "lin-2",
    "Português",
    "Variação linguística",
    "facil",
    'Em "Nóis vai na festa amanhã", registra-se um exemplo de variação',
    [
      "histórica",
      "regional apenas",
      "diafásica formal",
      "diastrática, ligada ao grupo social do falante",
      "inexistente, pois é apenas erro",
    ],
    3,
    "Trata-se de variação diastrática (social). Não há língua errada, mas adequação ao contexto.",
    "Inspirada no ENEM 2018",
  ],
  [
    "lin-3",
    "Português",
    "Figuras de linguagem",
    "facil",
    '"Meu coração é um balde despejado." (Fernando Pessoa). A figura de linguagem predominante é',
    ["metáfora", "metonímia", "hipérbole", "eufemismo", "ironia"],
    0,
    "Há comparação implícita entre coração e balde, característica da metáfora.",
    "Inspirada no ENEM 2016",
  ],
  [
    "lin-4",
    "Português",
    "Figuras de linguagem",
    "facil",
    'Em "Li Machado de Assis inteiro nas férias", ocorre',
    ["metáfora", "metonímia", "catacrese", "pleonasmo", "antítese"],
    1,
    "O autor é citado no lugar de sua obra: substituição típica da metonímia.",
    "Inspirada no ENEM 2017",
  ],
  [
    "lin-5",
    "Português",
    "Interpretação de texto",
    "media",
    'Um texto afirma: "A tecnologia aproxima quem está longe e afasta quem está perto". O recurso que sustenta o efeito de sentido é',
    [
      "a antítese entre aproximar e afastar",
      "a hipérbole do alcance da tecnologia",
      "a personificação da internet",
      "o eufemismo sobre isolamento",
      "a onomatopeia",
    ],
    0,
    'A oposição entre "aproxima" e "afasta", "longe" e "perto" configura antítese.',
    "Inspirada no ENEM 2021",
  ],
  [
    "lin-6",
    "Português",
    "Gêneros textuais",
    "facil",
    "Um texto que apresenta ingredientes e modo de preparo, com verbos no imperativo, pertence ao gênero",
    ["crônica", "receita", "editorial", "relatório", "resenha"],
    1,
    "A estrutura ingredientes + modo de preparo é típica da receita, gênero instrucional.",
    "Inspirada no ENEM 2015",
  ],
  [
    "lin-7",
    "Português",
    "Gêneros textuais",
    "facil",
    "O gênero que expressa a opinião oficial de um jornal sobre um fato atual chama-se",
    ["notícia", "reportagem", "editorial", "entrevista", "classificado"],
    2,
    "O editorial traz o posicionamento institucional do veículo, sem assinatura individual.",
    "Inspirada no ENEM 2018",
  ],
  [
    "lin-8",
    "Português",
    "Charges e tirinhas",
    "media",
    "Em uma tirinha, o efeito de humor costuma se concentrar",
    [
      "no primeiro quadrinho, que apresenta o cenário",
      "no último quadrinho, com a quebra de expectativa",
      "nas cores utilizadas pelo cartunista",
      "na ausência de balões de fala",
      "na descrição do narrador",
    ],
    1,
    "O humor da tirinha se apoia na quebra de expectativa apresentada no desfecho.",
    "Inspirada no ENEM 2020",
  ],
  [
    "lin-9",
    "Português",
    "Linguagem verbal e não verbal",
    "facil",
    "Uma placa de trânsito com um cigarro cortado por uma faixa vermelha comunica por meio de linguagem",
    [
      "exclusivamente verbal",
      "exclusivamente não verbal",
      "mista, com predomínio do verbal",
      "metalinguística",
      "coloquial",
    ],
    1,
    "A mensagem é transmitida apenas por imagem e símbolo, sem palavras: linguagem não verbal.",
    "Inspirada no ENEM 2016",
  ],
  [
    "lin-10",
    "Português",
    "Publicidade",
    "media",
    'Uma campanha usa o slogan "Beba água. Seu corpo agradece." O apelo publicitário se apoia principalmente',
    [
      "no humor irônico",
      "na personificação do corpo e no imperativo",
      "na linguagem técnica científica",
      "na intertextualidade literária",
      "na variação regional",
    ],
    1,
    'O corpo "agradece" (personificação) e o verbo no imperativo convoca o leitor à ação.',
    "Inspirada no ENEM 2019",
  ],
  [
    "lin-11",
    "Literatura",
    "Romantismo",
    "media",
    "O indianismo de José de Alencar, em obras como Iracema, tem como função central",
    [
      "criticar o Estado Novo",
      "construir um mito de origem nacional",
      "descrever a industrialização",
      "documentar a escravidão urbana",
      "defender o realismo científico",
    ],
    1,
    "O Romantismo indianista elege o indígena como herói fundador da identidade brasileira.",
    "Inspirada no ENEM 2017",
  ],
  [
    "lin-12",
    "Literatura",
    "Realismo",
    "media",
    "Machado de Assis, em Memórias Póstumas de Brás Cubas, inova ao",
    [
      "adotar narrador defunto e ironia sobre a elite",
      "escrever em versos alexandrinos",
      "abandonar a prosa pela dramaturgia",
      "exaltar o herói nacional idealizado",
      "narrar apenas o cotidiano rural",
    ],
    0,
    'O narrador "defunto autor" e a ironia contra a elite fluminense são marcas do Realismo machadiano.',
    "Inspirada no ENEM 2018",
  ],
  [
    "lin-13",
    "Literatura",
    "Modernismo",
    "media",
    "A Semana de Arte Moderna de 1922 defendeu, sobretudo,",
    [
      "o retorno às formas clássicas",
      "a ruptura com o academicismo e a valorização do falar brasileiro",
      "o parnasianismo como estética oficial",
      "o abandono da literatura pela pintura",
      "a censura à arte popular",
    ],
    1,
    "O movimento propôs liberdade formal e valorização da linguagem e da cultura brasileiras.",
    "Inspirada no ENEM 2022",
  ],
  [
    "lin-14",
    "Literatura",
    "Modernismo de 30",
    "media",
    "Vidas Secas, de Graciliano Ramos, destaca-se por",
    [
      "narrar a vida de nobres europeus",
      "retratar a seca e a exclusão social com linguagem seca e direta",
      "usar linguagem rebuscada e mitológica",
      "defender o ufanismo romântico",
      "apresentar final feliz idealizado",
    ],
    1,
    "A obra retrata retirantes nordestinos com estilo enxuto, coerente com a aridez do tema.",
    "Inspirada no ENEM 2016",
  ],
  [
    "lin-15",
    "Literatura",
    "Poesia contemporânea",
    "media",
    'Em textos de Carlos Drummond de Andrade como "No meio do caminho tinha uma pedra", a repetição produz efeito de',
    [
      "obstáculo e monotonia da existência",
      "alegria festiva",
      "erudição clássica",
      "descrição científica",
      "neutralidade jornalística",
    ],
    0,
    "A repetição insistente reforça a ideia de obstáculo permanente no percurso da vida.",
    "Inspirada no ENEM 2019",
  ],
  [
    "lin-16",
    "Português",
    "Coesão",
    "media",
    'Em "Estudou muito; portanto, foi aprovado", o conectivo destacado estabelece relação de',
    ["oposição", "conclusão", "adição", "concessão", "alternância"],
    1,
    '"Portanto" introduz a conclusão decorrente da informação anterior.',
    "Inspirada no ENEM 2017",
  ],
  [
    "lin-17",
    "Português",
    "Coesão",
    "facil",
    'Em "Ana comprou o livro e o leu em dois dias", o pronome "o" retoma',
    ["Ana", "o livro", "dois dias", "a compra", "a leitura"],
    1,
    'O pronome oblíquo retoma o termo antecedente "o livro", garantindo coesão referencial.',
    "Inspirada no ENEM 2015",
  ],
  [
    "lin-18",
    "Português",
    "Gramática aplicada",
    "media",
    "Assinale a frase em que a concordância verbal está de acordo com a norma-padrão.",
    [
      "Fazem dois anos que estudo aqui.",
      "Houveram muitos problemas ontem.",
      "Faz dois anos que estudo aqui.",
      "Existe muitos problemas na cidade.",
      "Deve haverem soluções melhores.",
    ],
    2,
    'O verbo "fazer" indicando tempo decorrido é impessoal e fica na 3ª pessoa do singular.',
    "Inspirada no ENEM 2018",
  ],
  [
    "lin-19",
    "Português",
    "Gramática aplicada",
    "media",
    'Em "Prefiro café a chá", a regência do verbo preferir está correta porque',
    [
      'exige a preposição "do que"',
      'exige objeto direto e indireto com a preposição "a"',
      "é intransitivo",
      "admite qualquer preposição",
      "dispensa complemento",
    ],
    1,
    'Preferir é transitivo direto e indireto: prefere-se algo a alguma coisa, sem "mais do que".',
    "Inspirada no ENEM 2020",
  ],
  [
    "lin-20",
    "Português",
    "Interpretação de texto",
    "media",
    'Um artigo começa afirmando: "Ninguém duvida de que ler faz bem — a discussão é como formar leitores". A estratégia usada é',
    [
      "negar o senso comum para chocar",
      "partir de um consenso para delimitar o problema real",
      "recorrer a dado estatístico",
      "usar linguagem informal para descontrair",
      "criar suspense narrativo",
    ],
    1,
    "O autor concorda com o consenso inicial e desloca o foco para o problema que pretende discutir.",
    "Inspirada no ENEM 2021",
  ],
  [
    "lin-21",
    "Português",
    "Intertextualidade",
    "media",
    'Uma propaganda que reescreve o verso "Minha terra tem palmeiras" para vender um resort utiliza',
    [
      "paráfrase sem relação com o original",
      "intertextualidade por paródia/apropriação criativa",
      "plágio inconsciente",
      "linguagem denotativa pura",
      "metalinguagem",
    ],
    1,
    "Há retomada explícita de um texto conhecido com nova finalidade: intertextualidade.",
    "Inspirada no ENEM 2019",
  ],
  [
    "lin-22",
    "Artes",
    "Arte moderna brasileira",
    "media",
    "A obra Abaporu, de Tarsila do Amaral, está associada ao movimento",
    ["Barroco", "Antropofágico", "Impressionista", "Renascentista", "Gótico"],
    1,
    "Abaporu (1928) inspirou o Manifesto Antropofágico de Oswald de Andrade.",
    "Inspirada no ENEM 2018",
  ],
  [
    "lin-23",
    "Artes",
    "Patrimônio cultural",
    "facil",
    "O frevo, o maracatu e o samba de roda são exemplos de",
    [
      "patrimônio material tombado",
      "patrimônio cultural imaterial brasileiro",
      "arte contemporânea europeia",
      "manifestações extintas",
      "gêneros literários",
    ],
    1,
    "São bens registrados como patrimônio imaterial por representarem saberes e práticas culturais vivas.",
    "Inspirada no ENEM 2017",
  ],
  [
    "lin-24",
    "Educação Física",
    "Corpo e sociedade",
    "facil",
    "A capoeira é reconhecida como manifestação que combina",
    [
      "apenas esporte de combate",
      "luta, dança, música e resistência cultural afro-brasileira",
      "ginástica olímpica europeia",
      "esporte criado no século XXI",
      "atividade exclusivamente recreativa",
    ],
    1,
    "A capoeira une elementos de luta, dança e música e é símbolo de resistência afro-brasileira.",
    "Inspirada no ENEM 2016",
  ],
  [
    "lin-25",
    "Inglês",
    "Interpretação",
    "facil",
    'Read: "Access to clean water is still a challenge for millions of people worldwide." O texto trata de',
    [
      "escassez de água potável no mundo",
      "aumento do turismo internacional",
      "avanços da inteligência artificial",
      "consumo de energia solar",
      "educação bilíngue",
    ],
    0,
    '"Access to clean water" indica que o tema é o acesso à água potável.',
    "Inspirada no ENEM 2019",
  ],
  [
    "lin-26",
    "Inglês",
    "Vocabulário",
    "facil",
    'In the sentence "Although she was tired, she finished the essay", the word "although" expresses',
    ["cause", "concession", "conclusion", "addition", "time"],
    1,
    '"Although" introduz ideia de concessão, equivalente a "embora".',
    "Inspirada no ENEM 2018",
  ],
  [
    "lin-27",
    "Português",
    "Semântica",
    "media",
    'Em "Ele é um leão nas provas", a palavra "leão" está empregada em sentido',
    ["denotativo", "conotativo", "arcaico", "técnico", "estrangeiro"],
    1,
    "O sentido é figurado (conotativo): indica coragem e força diante das provas.",
    "Inspirada no ENEM 2015",
  ],
  [
    "lin-28",
    "Português",
    "Tipologia textual",
    "facil",
    "Um texto que defende um ponto de vista com argumentos e proposta final é predominantemente",
    ["narrativo", "descritivo", "injuntivo", "dissertativo-argumentativo", "expositivo neutro"],
    3,
    "Defesa de tese com argumentos e conclusão caracteriza o texto dissertativo-argumentativo.",
    "Inspirada no ENEM 2021",
  ],
  [
    "lin-29",
    "Português",
    "Norma culta",
    "media",
    "Assinale a opção com uso adequado da crase.",
    [
      "Cheguei à casa de Maria.",
      "Cheguei à pé.",
      "Refiro-me à ele.",
      "Vou à Brasília.",
      "Entreguei à ela o livro.",
    ],
    0,
    'A crase ocorre com termo feminino determinado: "à casa de Maria". Antes de pronomes e palavras masculinas não há crase.',
    "Inspirada no ENEM 2020",
  ],
  [
    "lin-30",
    "Português",
    "Interpretação de texto",
    "dificil",
    'Um cronista escreve: "O celular virou uma extensão da mão — e, às vezes, uma prótese do pensamento". A crítica presente é',
    [
      "ao custo dos aparelhos",
      "à dependência cognitiva em relação à tecnologia",
      "à baixa qualidade das redes móveis",
      "ao excesso de aplicativos pagos",
      "à falta de acesso à internet no campo",
    ],
    1,
    'A metáfora "prótese do pensamento" critica a terceirização do raciocínio para o aparelho.',
    "Inspirada no ENEM 2022",
  ],
];
