/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EstatisticasRouteImport } from './routes/estatisticas'
import { Route as ListasRouteImport } from './routes/listas'
import { Route as RankingRouteImport } from './routes/ranking'
import { Route as RedacaoRouteImport } from './routes/redacao'
import { Route as SimuladosRouteImport } from './routes/simulados'
import { Route as VideosRouteImport } from './routes/videos'
import { Route as TreinarIndexRouteImport } from './routes/treinar/index'
import { Route as TreinarAreaRouteImport } from './routes/treinar/$area'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EstatisticasRoute = EstatisticasRouteImport.update({
  id: '/estatisticas',
  path: '/estatisticas',
  getParentRoute: () => rootRouteImport,
} as any)
const ListasRoute = ListasRouteImport.update({
  id: '/listas',
  path: '/listas',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingRoute = RankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => rootRouteImport,
} as any)
const RedacaoRoute = RedacaoRouteImport.update({
  id: '/redacao',
  path: '/redacao',
  getParentRoute: () => rootRouteImport,
} as any)
const SimuladosRoute = SimuladosRouteImport.update({
  id: '/simulados',
  path: '/simulados',
  getParentRoute: () => rootRouteImport,
} as any)
const VideosRoute = VideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => rootRouteImport,
} as any)
const TreinarIndexRoute = TreinarIndexRouteImport.update({
  id: '/treinar/',
  path: '/treinar/',
  getParentRoute: () => rootRouteImport,
} as any)
const TreinarAreaRoute = TreinarAreaRouteImport.update({
  id: '/treinar/$area',
  path: '/treinar/$area',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/estatisticas': typeof EstatisticasRoute
  '/listas': typeof ListasRoute
  '/ranking': typeof RankingRoute
  '/redacao': typeof RedacaoRoute
  '/simulados': typeof SimuladosRoute
  '/videos': typeof VideosRoute
  '/treinar/$area': typeof TreinarAreaRoute
  '/treinar/': typeof TreinarIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/estatisticas': typeof EstatisticasRoute
  '/listas': typeof ListasRoute
  '/ranking': typeof RankingRoute
  '/redacao': typeof RedacaoRoute
  '/simulados': typeof SimuladosRoute
  '/videos': typeof VideosRoute
  '/treinar/$area': typeof TreinarAreaRoute
  '/treinar': typeof TreinarIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/estatisticas': typeof EstatisticasRoute
  '/listas': typeof ListasRoute
  '/ranking': typeof RankingRoute
  '/redacao': typeof RedacaoRoute
  '/simulados': typeof SimuladosRoute
  '/videos': typeof VideosRoute
  '/treinar/$area': typeof TreinarAreaRoute
  '/treinar/': typeof TreinarIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/estatisticas'
    | '/listas'
    | '/ranking'
    | '/redacao'
    | '/simulados'
    | '/videos'
    | '/treinar/$area'
    | '/treinar/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/estatisticas'
    | '/listas'
    | '/ranking'
    | '/redacao'
    | '/simulados'
    | '/videos'
    | '/treinar/$area'
    | '/treinar'
  id:
    | '__root__'
    | '/'
    | '/estatisticas'
    | '/listas'
    | '/ranking'
    | '/redacao'
    | '/simulados'
    | '/videos'
    | '/treinar/$area'
    | '/treinar/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EstatisticasRoute: typeof EstatisticasRoute
  ListasRoute: typeof ListasRoute
  RankingRoute: typeof RankingRoute
  RedacaoRoute: typeof RedacaoRoute
  SimuladosRoute: typeof SimuladosRoute
  VideosRoute: typeof VideosRoute
  TreinarAreaRoute: typeof TreinarAreaRoute
  TreinarIndexRoute: typeof TreinarIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estatisticas': {
      id: '/estatisticas'
      path: '/estatisticas'
      fullPath: '/estatisticas'
      preLoaderRoute: typeof EstatisticasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listas': {
      id: '/listas'
      path: '/listas'
      fullPath: '/listas'
      preLoaderRoute: typeof ListasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ranking': {
      id: '/ranking'
      path: '/ranking'
      fullPath: '/ranking'
      preLoaderRoute: typeof RankingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redacao': {
      id: '/redacao'
      path: '/redacao'
      fullPath: '/redacao'
      preLoaderRoute: typeof RedacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulados': {
      id: '/simulados'
      path: '/simulados'
      fullPath: '/simulados'
      preLoaderRoute: typeof SimuladosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/videos': {
      id: '/videos'
      path: '/videos'
      fullPath: '/videos'
      preLoaderRoute: typeof VideosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/treinar/': {
      id: '/treinar/'
      path: '/treinar'
      fullPath: '/treinar/'
      preLoaderRoute: typeof TreinarIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/treinar/$area': {
      id: '/treinar/$area'
      path: '/treinar/$area'
      fullPath: '/treinar/$area'
      preLoaderRoute: typeof TreinarAreaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EstatisticasRoute: EstatisticasRoute,
  ListasRoute: ListasRoute,
  RankingRoute: RankingRoute,
  RedacaoRoute: RedacaoRoute,
  SimuladosRoute: SimuladosRoute,
  VideosRoute: VideosRoute,
  TreinarAreaRoute: TreinarAreaRoute,
  TreinarIndexRoute: TreinarIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
